name: Financial-Data-Analysis

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - yfinance # Yahoo Finance API
  - praw  # Reddit API
  - pip:    
    - python-dotenv      
    - torch       
    - transformers 
