name: Lint Python Files with Pylint (Using Cached Conda)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12

    - name: Restore Conda Cache
      id: cache-conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Create or Update Conda Environment
      run: |
        mkdir -p ~/conda_pkgs_dir
        conda config --add pkgs_dirs ~/conda_pkgs_dir
        conda env create --file environment.yml || conda env update --file environment.yml --prune
        conda list -n Financial-Data-Analysis  # Verify environment creation

    - name: Run Pylint
      run: conda run -n Financial-Data-Analysis pylint **/*.py
